from typing import Dict

_PROVIDER_KEY_MAP: Dict[str, str] = {
    "deepseek":    "DEEPSEEK_API_KEY",
    "openai":      "OPENAI_API_KEY",
    "anthropic":   "ANTHROPIC_API_KEY",
    "claude":      "ANTHROPIC_API_KEY",
    "groq":        "GROQ_API_KEY",
    "together":    "TOGETHER_API_KEY",
    "google":      "GOOGLE_API_KEY",
    "gemini":      "GOOGLE_API_KEY",
    "xai":         "XAI_API_KEY",
    "grok":        "XAI_API_KEY",
    "mistral":     "MISTRAL_API_KEY",
    "cohere":      "COHERE_API_KEY",
    "perplexity":  "PERPLEXITY_API_KEY",
    "dashscope":   "DASHSCOPE_API_KEY",
    "aliyun":      "DASHSCOPE_API_KEY",
    "siliconflow": "SILICONFLOW_API_KEY",
    "moonshot":    "MOONSHOT_API_KEY",
    "zhipu":       "ZHIPUAI_API_KEY",
    "glm":         "ZHIPUAI_API_KEY",
    "baidu":       "QIANFAN_ACCESS_KEY",
    "ernie":       "QIANFAN_ACCESS_KEY",
    "qianfan":     "QIANFAN_ACCESS_KEY",
    "bytedance":   "ARK_API_KEY",
    "doubao":      "ARK_API_KEY",
    "ark":         "ARK_API_KEY",
    "minimax":     "MINIMAX_API_KEY",
    "stepfun":     "STEPFUN_API_KEY",
    "01ai":        "ONEAI_API_KEY",
    "yi":          "ONEAI_API_KEY",
}

_DATA_KEY_MAP: Dict[str, str] = {
    "finnhub":      "FINNHUB_API_KEY",
    "newsapi":      "NEWS_API_KEY",
    "brave":        "BRAVE_SEARCH_API_KEY",
    "tavily":       "TAVILY_API_KEY",
    "coingecko":    "COINGECKO_API_KEY",
    "alphavantage": "ALPHA_VANTAGE_API_KEY",
    "polygon":      "POLYGON_API_KEY",
    "fmp":          "FMP_API_KEY",
    "twelvedata":   "TWELVEDATA_API_KEY",
    "figma":        "FIGMA_API_KEY",
}

_DATA_SIGNUP_URLS: Dict[str, str] = {
    "finnhub":      "https://finnhub.io/register",
    "newsapi":      "https://newsapi.org/register",
    "brave":        "https://api.search.brave.com/app/keys",
    "tavily":       "https://app.tavily.com",
    "coingecko":    "https://www.coingecko.com/en/api",
    "alphavantage": "https://www.alphavantage.co/support/#api-key",
    "polygon":      "https://polygon.io/signup",
    "fmp":          "https://financialmodelingprep.com/register",
    "twelvedata":   "https://twelvedata.com/register",
    "figma":        "https://www.figma.com/developers/api#access-tokens",
}

_LLM_SIGNUP_URLS: Dict[str, str] = {
    "deepseek":    "https://platform.deepseek.com/api_keys",
    "openai":      "https://platform.openai.com/api-keys",
    "anthropic":   "https://console.anthropic.com/settings/keys",
    "claude":      "https://console.anthropic.com/settings/keys",
    "groq":        "https://console.groq.com/keys",
    "together":    "https://api.together.ai/settings/api-keys",
    "google":      "https://aistudio.google.com/app/apikey",
    "gemini":      "https://aistudio.google.com/app/apikey",
    "xai":         "https://console.x.ai",
    "grok":        "https://console.x.ai",
    "mistral":     "https://console.mistral.ai/api-keys",
    "cohere":      "https://dashboard.cohere.com/api-keys",
    "perplexity":  "https://www.perplexity.ai/settings/api",
    "dashscope":   "https://dashscope.console.aliyun.com/apiKey",
    "aliyun":      "https://dashscope.console.aliyun.com/apiKey",
    "siliconflow": "https://cloud.siliconflow.cn/account/ak",
    "moonshot":    "https://platform.moonshot.cn/console/api-keys",
    "zhipu":       "https://open.bigmodel.cn/usercenter/apikeys",
    "baidu":       "https://qianfan.cloud.baidu.com/user/accessToken",
    "ernie":       "https://qianfan.cloud.baidu.com/user/accessToken",
    "bytedance":   "https://ark.volcengine.com/api-key",
    "doubao":      "https://ark.volcengine.com/api-key",
    "minimax":     "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    "stepfun":     "https://platform.stepfun.com/interface-key",
    "01ai":        "https://platform.lingyiwanwu.com/apikeys",
    "yi":          "https://platform.lingyiwanwu.com/apikeys",
}
