"""
markdown_pdf.py — Markdown 报告 → 印刷级排版 HTML/PDF（中英双语模板）
=====================================================================
与 report_generator.py（HTML 研报引擎）互补：本模块面向**Markdown 交付物**
（/report --format md 的投研报告、分析纪要、任何模型生成的 md 文本），
渲染成专业浅色印刷模板后走 report_generator.export_pdf 引擎链出 PDF。

模板特性（与 Arthera research 渲染管线同源）:
  · 真表格：深色列头、斑马纹、跨页重复表头（thead）
  · 信号徽章着色：买入/BUY 绿 · 减仓/REDUCE 琥珀 · 卖出/SELL 红 · 持有/HOLD 灰
  · 首个引用块升级为元信息条（生成时间 | 数据截止 …）
  · 打印分页规则：@page A4、表格行不跨页断裂、章节标题不孤行
  · lang="zh" / "en" 切换模板文案（页脚、免责声明）；"auto" 按内容检测

PDF 分页取决于引擎：headless Chrome（推荐，完整 @page 支持）；
macOS WebKit 兜底为单长页（内容完整，无分页）。

对外:
  render_markdown_html(md_text, lang="auto", title=None) -> str
  markdown_to_pdf(md_text_or_path, pdf_path, lang="auto") -> Optional[Path]
  tool_export_markdown_pdf(params) + register_markdown_pdf_tools(...)
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

try:
    import markdown as _markdown
    HAS_MARKDOWN = True
except ImportError:
    HAS_MARKDOWN = False

_LABELS = {
    "zh": {
        "footer": "本报告由 Aria 确定性渲染管线生成",
        "disclaimer": "仅供研究参考，不构成投资建议",
    },
    "en": {
        "footer": "Generated by the Aria deterministic render pipeline",
        "disclaimer": "For research reference only — not investment advice",
    },
}

_BADGES = [
    (r"买入|BUY|STRONG_BUY", "#0a7a43", "#e6f6ec"),
    (r"减仓|REDUCE", "#8a5b00", "#fdf3d7"),
    (r"卖出|SELL|离场|EXIT", "#b91c1c", "#fdeaea"),
    (r"持有|HOLD|观望|WATCH", "#4b5563", "#eef1f4"),
    (r"共振|CONFIRMS?", "#0a6e8a", "#e3f4f9"),
    (r"分歧|DIVERGES?", "#a16207", "#fdf3d7"),
]

_CSS = """
@page { size: A4; margin: 14mm 12mm 16mm 12mm; }
* { box-sizing: border-box; }
body { font-family: -apple-system, "PingFang SC", "Hiragino Sans GB",
       "Microsoft YaHei", "Noto Sans CJK SC", "Segoe UI", sans-serif;
       color: #1a202c; background: #fff; font-size: 10.5pt;
       line-height: 1.55; margin: 0; }
.page { max-width: 186mm; margin: 0 auto; }
h1 { font-size: 19pt; margin: 0 0 4px; padding-bottom: 8px;
     border-bottom: 3px solid #1f2937; }
h2 { font-size: 13pt; margin: 22px 0 8px; padding: 6px 10px;
     background: #f3f5f8; border-left: 4px solid #334155;
     border-radius: 3px; page-break-after: avoid; }
h3 { font-size: 11.5pt; margin: 14px 0 6px; page-break-after: avoid; }
p { margin: 6px 0; }
hr { border: none; border-top: 1px solid #e2e8f0; margin: 14px 0; }
.meta { display: flex; flex-wrap: wrap; gap: 6px 14px; align-items: center;
        background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px;
        padding: 8px 12px; margin: 10px 0 4px; font-size: 9pt; color: #334155; }
.meta b, .meta strong { color: #0f172a; }
blockquote { margin: 8px 0; padding: 6px 12px; font-size: 9.5pt;
             color: #57534e; background: #fffbeb;
             border-left: 3px solid #d97706; border-radius: 3px; }
blockquote p { margin: 2px 0; }
table { border-collapse: collapse; width: 100%; margin: 10px 0 14px;
        font-size: 9pt; page-break-inside: auto; }
thead { display: table-header-group; }
tr { page-break-inside: avoid; }
th { background: #1f2937; color: #fff; font-weight: 600; padding: 6px 8px;
     text-align: left; white-space: nowrap; }
td { border: 1px solid #e2e8f0; padding: 5px 8px; vertical-align: top; }
tbody tr:nth-child(even) { background: #f8fafc; }
td:first-child { white-space: nowrap; }
/* Wide-table auto-fit: shrink font/padding by column count so content
   never crosses the page boundary (classes added by _fit_wide_tables). */
table.t-wide  { font-size: 7.5pt; }
table.t-wide  th, table.t-wide  td { padding: 4px 5px; }
table.t-xwide { font-size: 6.8pt; }
table.t-xwide th, table.t-xwide td { padding: 3px 4px; }
table.t-wide th, table.t-xwide th { white-space: normal; }
table.t-wide td, table.t-xwide td { word-break: keep-all; overflow-wrap: break-word; }
table.t-wide  td:nth-child(-n+2),
table.t-xwide td:nth-child(-n+2) { white-space: nowrap; }
table.t-wide  .badge { font-size: 7pt;  padding: 1px 5px; }
table.t-xwide .badge { font-size: 6.3pt; padding: 0 4px; }
.badge { display: inline-block; padding: 1px 7px; border-radius: 10px;
         font-size: 8.5pt; font-weight: 600; white-space: nowrap; }
ul, ol { margin: 6px 0; padding-left: 22px; }
li { margin: 3px 0; }
code { font-family: "SF Mono", Menlo, Consolas, monospace;
       background: #f1f5f9; padding: 1px 5px; border-radius: 3px;
       font-size: 9pt; }
pre { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px;
      padding: 10px 12px; overflow-x: auto; page-break-inside: avoid; }
pre code { background: none; padding: 0; }
strong { color: #0f172a; }
.footer { margin-top: 26px; padding-top: 8px;
          border-top: 1px solid #e2e8f0; font-size: 8pt;
          color: #94a3b8; text-align: center; }
"""


def detect_lang(md_text: str) -> str:
    """内容含 CJK 字符占比 > 5% 判为中文。"""
    if not md_text:
        return "en"
    cjk = sum(1 for ch in md_text[:4000] if "一" <= ch <= "鿿")
    return "zh" if cjk > len(md_text[:4000]) * 0.05 else "en"


def _apply_badges(html: str) -> str:
    def _decorate_cell(m: re.Match) -> str:
        cell = m.group(0)
        for pat, fg, bg in _BADGES:
            cell = re.sub(
                rf"((?:🟢|🟡|🔴|⬜|✅|⚠️|➖)?\s*(?:<strong>)?(?:{pat})(?:</strong>)?)",
                rf'<span class="badge" style="color:{fg};background:{bg}">\1</span>',
                cell, count=1,
            )
        return cell
    return re.sub(r"<td>.*?</td>", _decorate_cell, html, flags=re.S)


def _fit_wide_tables(html: str) -> str:
    """≥12 列 → t-xwide (6.8pt)；≥9 列 → t-wide (7.5pt)：按边界自适应字号。"""
    def _tag(m: re.Match) -> str:
        table = m.group(0)
        head = table.split("</tr>", 1)[0]
        n = len(re.findall(r"<th[ >]", head))
        if n >= 12:
            cls = "t-xwide"
        elif n >= 9:
            cls = "t-wide"
        else:
            return table
        return re.sub(r"<table>", f'<table class="{cls}">', table, count=1)
    return re.sub(r"<table>.*?</table>", _tag, html, flags=re.S)


def _promote_meta_bar(html: str) -> str:
    return re.sub(
        r"(</h1>\s*)<blockquote>(.*?)</blockquote>",
        lambda m: m.group(1) + '<div class="meta">'
                  + re.sub(r"</?p>", "", m.group(2)).replace("|", "·")
                  + "</div>",
        html, count=1, flags=re.S,
    )


def render_markdown_html(md_text: str, lang: str = "auto",
                         title: Optional[str] = None) -> str:
    """Markdown 文本 → 完整可打印 HTML 文档（浅色印刷模板）。"""
    if not HAS_MARKDOWN:
        raise RuntimeError("python-markdown 未安装: pip install markdown")
    if lang == "auto":
        lang = detect_lang(md_text)
    labels = _LABELS.get(lang, _LABELS["en"])

    body = _markdown.markdown(
        md_text, extensions=["tables", "sane_lists", "nl2br", "fenced_code"],
        output_format="html5",
    )
    body = _promote_meta_bar(body)
    body = _apply_badges(body)
    body = _fit_wide_tables(body)

    if not title:
        m = re.search(r"<h1[^>]*>(.*?)</h1>", body, re.S)
        title = re.sub(r"<[^>]+>", "", m.group(1)) if m else "Report"
    footer = (f"{labels['footer']} · {datetime.now():%Y-%m-%d %H:%M} · "
              f"{labels['disclaimer']}")
    return (
        f'<!doctype html><html lang="{lang}"><head><meta charset="utf-8">'
        f"<title>{title}</title><style>{_CSS}</style></head>"
        f'<body><div class="page">{body}'
        f'<div class="footer">{footer}</div></div></body></html>'
    )


def markdown_to_pdf(md: str | Path, pdf_path: Path,
                    lang: str = "auto") -> Optional[Path]:
    """Markdown（文本或 .md 路径）→ 排版 PDF。返回 PDF 路径，失败 None。"""
    md_text = (Path(md).read_text(encoding="utf-8")
               if isinstance(md, Path) or (isinstance(md, str)
                   and len(md) < 512 and Path(md).expanduser().is_file())
               else str(md))
    html = render_markdown_html(md_text, lang=lang)
    from aria_code.report_generator import html_string_to_pdf
    return html_string_to_pdf(html, Path(pdf_path))


# ── Agent 工具 ───────────────────────────────────────────────────────────────

def tool_export_markdown_pdf(params: Dict[str, Any]) -> Dict[str, Any]:
    """LOCAL_TOOLS 入口。params: {markdown|md_path, filename?, lang?}"""
    try:
        md = params.get("markdown") or params.get("md_path")
        if not md:
            return {"success": False, "error": "缺少 markdown 或 md_path"}
        lang = params.get("lang", "auto")
        stem = str(params.get("filename") or "report").removesuffix(".pdf")
        try:
            from aria_code.artifacts import create_user_artifact
            record = create_user_artifact("reports", params.get("topic"),
                                          stem, ".pdf")
            pdf_path = record.path
        except Exception:
            pdf_path = Path.cwd() / f"{stem}.pdf"
        source = Path(md) if (isinstance(md, str) and len(md) < 512
                              and Path(md).expanduser().is_file()) else md
        out = markdown_to_pdf(source, pdf_path, lang=lang)
        if out is None:
            return {"success": False,
                    "error": "无可用 PDF 引擎（安装 Chrome/Edge，"
                             "或 macOS: pip install pyobjc-framework-WebKit）"}
        return {"success": True, "path": str(out),
                "size_kb": out.stat().st_size // 1024,
                "lang": lang if lang != "auto" else detect_lang(
                    md if isinstance(md, str) else Path(md).read_text(encoding="utf-8")[:4000])}
    except Exception as exc:
        logger.debug("[md-pdf] export error: %s", exc, exc_info=True)
        return {"success": False, "error": str(exc)}


MARKDOWN_PDF_TOOL_SCHEMAS: List[Dict[str, Any]] = [
    {
        "type": "function",
        "function": {
            "name": "export_markdown_pdf",
            "description": (
                "把 Markdown 报告渲染成专业排版 PDF（印刷级模板：真表格、"
                "信号徽章着色、元信息条、A4 分页）。支持中英文模板"
                "（lang: zh/en/auto，auto 按内容检测）。传 markdown 原文"
                "或 md_path 文件路径均可；返回 PDF 路径。"
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "markdown": {"type": "string",
                                 "description": "Markdown 原文（与 md_path 二选一）"},
                    "md_path": {"type": "string",
                                "description": "Markdown 文件路径（与 markdown 二选一）"},
                    "filename": {"type": "string",
                                 "description": "输出文件名（不含扩展名）"},
                    "topic": {"type": "string", "description": "产物子目录主题"},
                    "lang": {"type": "string", "enum": ["auto", "zh", "en"],
                             "description": "模板语言，默认 auto"},
                },
                "required": [],
            },
        },
    },
]


def register_markdown_pdf_tools(tool_registry: Dict, schema_registry: List) -> int:
    if not HAS_MARKDOWN:
        return 0
    added = 0
    if "export_markdown_pdf" not in tool_registry:
        tool_registry["export_markdown_pdf"] = (
            tool_export_markdown_pdf,
            "Markdown 报告 → 专业排版 PDF（中英双语模板）",
        )
        added += 1
    existing = {s.get("function", {}).get("name") for s in schema_registry}
    for schema in MARKDOWN_PDF_TOOL_SCHEMAS:
        if schema["function"]["name"] not in existing:
            schema_registry.append(schema)
    return added
