#!/bin/bash
mkdir -p src/aria_code
touch src/aria_code/__init__.py
git mv aliyun_data_client.py src/aria_code/aliyun_data_client.py 2>/dev/null || mv aliyun_data_client.py src/aria_code/aliyun_data_client.py
git mv aria_cli.py src/aria_code/aria_cli.py 2>/dev/null || mv aria_cli.py src/aria_code/aria_cli.py
git mv aria_daemon.py src/aria_code/aria_daemon.py 2>/dev/null || mv aria_daemon.py src/aria_code/aria_daemon.py
git mv aria_feishu_bot.py src/aria_code/aria_feishu_bot.py 2>/dev/null || mv aria_feishu_bot.py src/aria_code/aria_feishu_bot.py
git mv aria_mcp_server.py src/aria_code/aria_mcp_server.py 2>/dev/null || mv aria_mcp_server.py src/aria_code/aria_mcp_server.py
git mv aria_relay_client.py src/aria_code/aria_relay_client.py 2>/dev/null || mv aria_relay_client.py src/aria_code/aria_relay_client.py
git mv aria_relay_server.py src/aria_code/aria_relay_server.py 2>/dev/null || mv aria_relay_server.py src/aria_code/aria_relay_server.py
git mv aria_telegram_bot.py src/aria_code/aria_telegram_bot.py 2>/dev/null || mv aria_telegram_bot.py src/aria_code/aria_telegram_bot.py
git mv ariarc.py src/aria_code/ariarc.py 2>/dev/null || mv ariarc.py src/aria_code/ariarc.py
git mv artifacts.py src/aria_code/artifacts.py 2>/dev/null || mv artifacts.py src/aria_code/artifacts.py
git mv backtest_engine.py src/aria_code/backtest_engine.py 2>/dev/null || mv backtest_engine.py src/aria_code/backtest_engine.py
git mv backtest_report.py src/aria_code/backtest_report.py 2>/dev/null || mv backtest_report.py src/aria_code/backtest_report.py
git mv canva_client.py src/aria_code/canva_client.py 2>/dev/null || mv canva_client.py src/aria_code/canva_client.py
git mv change_store.py src/aria_code/change_store.py 2>/dev/null || mv change_store.py src/aria_code/change_store.py
git mv command_safety.py src/aria_code/command_safety.py 2>/dev/null || mv command_safety.py src/aria_code/command_safety.py
git mv computer_use_tools.py src/aria_code/computer_use_tools.py 2>/dev/null || mv computer_use_tools.py src/aria_code/computer_use_tools.py
git mv dashboard_generator.py src/aria_code/dashboard_generator.py 2>/dev/null || mv dashboard_generator.py src/aria_code/dashboard_generator.py
git mv data_analysis_tools.py src/aria_code/data_analysis_tools.py 2>/dev/null || mv data_analysis_tools.py src/aria_code/data_analysis_tools.py
git mv data_cleaner.py src/aria_code/data_cleaner.py 2>/dev/null || mv data_cleaner.py src/aria_code/data_cleaner.py
git mv data_service.py src/aria_code/data_service.py 2>/dev/null || mv data_service.py src/aria_code/data_service.py
git mv demo_player.py src/aria_code/demo_player.py 2>/dev/null || mv demo_player.py src/aria_code/demo_player.py
git mv doctor.py src/aria_code/doctor.py 2>/dev/null || mv doctor.py src/aria_code/doctor.py
git mv external_agent_runner.py src/aria_code/external_agent_runner.py 2>/dev/null || mv external_agent_runner.py src/aria_code/external_agent_runner.py
git mv figma_client.py src/aria_code/figma_client.py 2>/dev/null || mv figma_client.py src/aria_code/figma_client.py
git mv file_analysis_tools.py src/aria_code/file_analysis_tools.py 2>/dev/null || mv file_analysis_tools.py src/aria_code/file_analysis_tools.py
git mv finance_formulas.py src/aria_code/finance_formulas.py 2>/dev/null || mv finance_formulas.py src/aria_code/finance_formulas.py
git mv football_data_client.py src/aria_code/football_data_client.py 2>/dev/null || mv football_data_client.py src/aria_code/football_data_client.py
git mv image_gen_tools.py src/aria_code/image_gen_tools.py 2>/dev/null || mv image_gen_tools.py src/aria_code/image_gen_tools.py
git mv intent_classifier.py src/aria_code/intent_classifier.py 2>/dev/null || mv intent_classifier.py src/aria_code/intent_classifier.py
git mv kling_video_client.py src/aria_code/kling_video_client.py 2>/dev/null || mv kling_video_client.py src/aria_code/kling_video_client.py
git mv licensing.py src/aria_code/licensing.py 2>/dev/null || mv licensing.py src/aria_code/licensing.py
git mv local_finance_tools.py src/aria_code/local_finance_tools.py 2>/dev/null || mv local_finance_tools.py src/aria_code/local_finance_tools.py
git mv local_image_provider.py src/aria_code/local_image_provider.py 2>/dev/null || mv local_image_provider.py src/aria_code/local_image_provider.py
git mv local_llm_provider.py src/aria_code/local_llm_provider.py 2>/dev/null || mv local_llm_provider.py src/aria_code/local_llm_provider.py
git mv macro_tools.py src/aria_code/macro_tools.py 2>/dev/null || mv macro_tools.py src/aria_code/macro_tools.py
git mv markdown_pdf.py src/aria_code/markdown_pdf.py 2>/dev/null || mv markdown_pdf.py src/aria_code/markdown_pdf.py
git mv market_data_client.py src/aria_code/market_data_client.py 2>/dev/null || mv market_data_client.py src/aria_code/market_data_client.py
git mv mcp_client.py src/aria_code/mcp_client.py 2>/dev/null || mv mcp_client.py src/aria_code/mcp_client.py
git mv memory_manager.py src/aria_code/memory_manager.py 2>/dev/null || mv memory_manager.py src/aria_code/memory_manager.py
git mv model_capability.py src/aria_code/model_capability.py 2>/dev/null || mv model_capability.py src/aria_code/model_capability.py
git mv notification_tools.py src/aria_code/notification_tools.py 2>/dev/null || mv notification_tools.py src/aria_code/notification_tools.py
git mv openai_image_client.py src/aria_code/openai_image_client.py 2>/dev/null || mv openai_image_client.py src/aria_code/openai_image_client.py
git mv plan_utils.py src/aria_code/plan_utils.py 2>/dev/null || mv plan_utils.py src/aria_code/plan_utils.py
git mv plugin_loader.py src/aria_code/plugin_loader.py 2>/dev/null || mv plugin_loader.py src/aria_code/plugin_loader.py
git mv portfolio_ledger.py src/aria_code/portfolio_ledger.py 2>/dev/null || mv portfolio_ledger.py src/aria_code/portfolio_ledger.py
git mv preview_server.py src/aria_code/preview_server.py 2>/dev/null || mv preview_server.py src/aria_code/preview_server.py
git mv project_tools.py src/aria_code/project_tools.py 2>/dev/null || mv project_tools.py src/aria_code/project_tools.py
git mv realty_data_tools.py src/aria_code/realty_data_tools.py 2>/dev/null || mv realty_data_tools.py src/aria_code/realty_data_tools.py
git mv report_exporters.py src/aria_code/report_exporters.py 2>/dev/null || mv report_exporters.py src/aria_code/report_exporters.py
git mv report_generator.py src/aria_code/report_generator.py 2>/dev/null || mv report_generator.py src/aria_code/report_generator.py
git mv runway_video_client.py src/aria_code/runway_video_client.py 2>/dev/null || mv runway_video_client.py src/aria_code/runway_video_client.py
git mv setup_wizard.py src/aria_code/setup_wizard.py 2>/dev/null || mv setup_wizard.py src/aria_code/setup_wizard.py
git mv spreadsheet_tools.py src/aria_code/spreadsheet_tools.py 2>/dev/null || mv spreadsheet_tools.py src/aria_code/spreadsheet_tools.py
git mv strategy_vault.py src/aria_code/strategy_vault.py 2>/dev/null || mv strategy_vault.py src/aria_code/strategy_vault.py
git mv video_analysis.py src/aria_code/video_analysis.py 2>/dev/null || mv video_analysis.py src/aria_code/video_analysis.py
git mv video_editor.py src/aria_code/video_editor.py 2>/dev/null || mv video_editor.py src/aria_code/video_editor.py
git mv workspace_context.py src/aria_code/workspace_context.py 2>/dev/null || mv workspace_context.py src/aria_code/workspace_context.py
git mv adk_apps src/aria_code/adk_apps 2>/dev/null || mv adk_apps src/aria_code/adk_apps
git mv agents src/aria_code/agents 2>/dev/null || mv agents src/aria_code/agents
git mv apps src/aria_code/apps 2>/dev/null || mv apps src/aria_code/apps
git mv brokers src/aria_code/brokers 2>/dev/null || mv brokers src/aria_code/brokers
git mv clients src/aria_code/clients 2>/dev/null || mv clients src/aria_code/clients
git mv datasources src/aria_code/datasources 2>/dev/null || mv datasources src/aria_code/datasources
git mv domain src/aria_code/domain 2>/dev/null || mv domain src/aria_code/domain
git mv packages src/aria_code/packages 2>/dev/null || mv packages src/aria_code/packages
git mv privacy src/aria_code/privacy 2>/dev/null || mv privacy src/aria_code/privacy
git mv providers src/aria_code/providers 2>/dev/null || mv providers src/aria_code/providers
git mv runtime src/aria_code/runtime 2>/dev/null || mv runtime src/aria_code/runtime
git mv safety src/aria_code/safety 2>/dev/null || mv safety src/aria_code/safety
git mv tools src/aria_code/tools 2>/dev/null || mv tools src/aria_code/tools
git mv ui src/aria_code/ui 2>/dev/null || mv ui src/aria_code/ui
git mv workspace src/aria_code/workspace 2>/dev/null || mv workspace src/aria_code/workspace
